on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-b = "workspace B"
alt-t = "workspace T"
alt-u = "workspace U"
alt-d = "workspace D"
alt-e = "workspace E"
alt-c = "workspace C"

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-e = 'move-node-to-workspace E'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

alt-shift-f = 'fullscreen'

[gaps]
    inner.horizontal = 18
    inner.vertical =   18
    outer.left =       10
    outer.bottom =     18
    outer.top =        18
    outer.right =      10

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-down = ['join-with down', 'mode main']
    alt-shift-up = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  run = 'move-node-to-workspace B'
[[on-window-detected]]
  if.app-id = 'com.mitchellh.ghostty'
  run = 'move-node-to-workspace T'
[[on-window-detected]]
  if.app-id = 'com.apple.finder'
  run = 'move-node-to-workspace U'
[[on-window-detected]]
  if.app-id = 'com.postmanlabs.mac'
  run = 'move-node-to-workspace U'
[[on-window-detected]]
  if.app-id = 'org.jkiss.dbeaver.core.product'
  run = 'move-node-to-workspace D'



